name: Publish Release

on:
  release:
    types:
      - created

jobs:
  godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, osx, win32, win64]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.1.0
        with:
          submodules: 'true'
          token: ${{ secrets.GH_SECRET }}
      - name: Configure
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          if [ "$PLATFORM" = "win32" ] || [ "$PLATFORM" = "win64" ] ; then
            echo "::set-env name=EXPORT_NAME::the-connection.exe"
          else
            echo "::set-env name=EXPORT_NAME::the-connection" 
          fi
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: ${{ env.EXPORT_NAME }}
          preset: ${{ matrix.platform }}
          projectDir: client
      - id: get_tag
        name: Get Tag
        env:
          GITHUB_HEAD_REF: $${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
        run: |
          TAG=$(jq --raw-output '.release.tag_name' $GITHUB_EVENT_PATH)
          echo ::set-output name=TAG::$TAG
      - name: Push to Itch
        uses: josephbmanley/butler-publish-itchio-action@v1.0.1
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.platform }}
          ITCH_GAME: the-connection
          ITCH_USER: josephbmanley
          PACKAGE: ${{ github.workspace }}/${{ steps.build.outputs.build }}
          VERSION: ${{ steps.get_tag.outputs.TAG }}